// src/components/Peeps.jsx
import { useQuery } from "react-query";

function Peeps() {
  const { isLoading, error, data } = useQuery("repoData", () =>
    fetch("https://chitter-backend-api-v2.herokuapp.com/peeps").then((res) =>
      res.json()
    )
  );

  if (isLoading) return "Loading...";

  if (error) return "An error has occurred: " + error.message;

  return (
    <div className="peeps-container">
      {data.map((peep, index) => {
        return (
          <div
            key={index}
            className="peep container w-1/2 mx-auto px-5 border-solid border-2 border-sky-500 my-2 rounded"
          >
            <p className="">{`User: ${peep.user.handle}`}</p>
            <p>{`Body: ${peep.body}`}</p>
            <p>{`Created at: ${peep.created_at}`}</p>
          </div>
        );
      })}
    </div>
  );
}

export default Peeps;

// src/views/Peeps.vue
<template>
  <div class="title">
    <h1>Chitter</h1>
    <div class="peeps">
      <div class="peep" v-for="peep in peeps">
        <h2>{{peep.body}}</h2>
        <h2>{{peep.user.handle}}</h2>
      </div>
    </div>
  </div>
</template>

<script>
import axios from 'axios'

export default {
  name: 'Peeps',
  data: function(){
    return {
      peeps: []
    }
  },
  created: function(){
    var self = this;

    axios.get('https://chitter-backend-api.herokuapp.com/peeps')
    .then(function (response) {
      self.peeps = response.data;
    })
    .catch(function (error) {
      console.log(error);
    });
  }
}
</script>

<style>
img {
  max-width: 50vw;
}
</style>
